from dotenv import load_dotenv
import os
from werkzeug.security import generate_password_hash
from pprint import pprint 



load_dotenv()



cohss_programmes = {
    'College of Humanities and Social Sciences': {
        'Faculty of Law': {
            'Faculty of Law':[
            'LL.B,'
            'LL.B (PARALLEL  (POST FIRST DEGREE))',
            'LL.B (PART-TIME (DEGREE HOLDERS ONLY))',
            'LL.M',
            'PHD. LAW'
            ]
        },

        'Faculty of Social Sciences': {
            'Department of Economics': [
                'MASTER OF PUBLIC ADMINISTRATION (WEEKEND)', 'BA. ECONOMICS, BA. ECONOMICS (PARALLEL)', 'MPHIL. ECONOMICS', 'MSC. BUSINESS ECONOMICS', 
                'MSC. ECONOMICS', 'MSC. ECONOMICS AND FINANCE', 'MSC. HEALTH ECONOMICS', 'PHD. ECONOMICS'
            ],
            'Department of English': [
                'BA. ENGLISH', 'BA. ENGLISH (PARALLEL)', 'MPHIL. ENGLISH', 'PHD. ENGLISH'
            ],
            'Department of Geography and Rural Development': [
                'BA. CULTURE AND TOURISM', 'BA. CULTURE AND TOURISM (PARALLEL)', 'BA. GEOGRAPHY AND RURAL DEVELOPMENT', 'BA. GEOGRAPHY AND RURAL DEVELOPMENT (PARALLEL)', 
                'MPHIL. GEOGRAPHY AND RURAL DEVELOPMENT', 'MSC. GEOGRAPHY AND SUSTAINABLE DEVELOPMENT', 'PHD. GEOGRAPHY AND RURAL DEVELOPMENT'
            ],
            'Department of History and Political Studies': [
                'BA. HISTORY', 'BA. HISTORY (PARALLEL)', 'BA. POLITICAL STUDIES', 'BA. POLITICAL STUDIES (PARALLEL)', 'BACHELOR OF PUBLIC ADMINISTRATION', 'MA. ASANTE HISTORY', 
                'MA. POLITICAL SCIENCE', 'MASTER OF PUBLIC ADMINISTRATION', 'MPHIL. HISTORICAL STUDIES', 'MPHIL. POLITICAL SCIENCE', 'PHD. HISTORICAL STUDIES', 'PHD. POLITICAL SCIENCE'
            ],
            'Department of Languages And Communication Sciences': [
                'BA. AKAN', 'BA. AKAN LANGUAGE AND CULTURE', 'BA. AKAN LANGUAGE AND CULTURE(PARALLEL)', 'BA. FRENCH', 'BA. FRENCH AND FRANCOPHONE STUDIES', 'BA. LINGUISTICS', 'BA. LINGUISTICS (PARALLEL)', 
                'BA. MEDIA AND COMMUNICATION STUDIES', 'BA. MEDIA AND COMMUNICATION STUDIES (PARALLEL)', 'MPHIL. FRENCH AND FRANCOPHONE STUDIES', 'PHD. FRENCH AND FRANCOPHONE STUDIES'
            ],
            'Department of Religion and Human Development': [
                'BA. RELIGION AND HUMAN DEVELOPMENT', 'BA. RELIGIOUS STUDIES', 'BA. RELIGIOUS STUDIES (PARALLEL)', 'MA. RELIGION AND HUMAN DEVELOPMENT', 'MA. RELIGIOUS STUDIES', 
                'MPHIL. RELIGION AND HUMAN DEVELOPMENT', 'MPHIL. RELIGIOUS STUDIES', 'PHD. RELIGION AND HUMAN DEVELOPMENT', 'PHD. RELIGIOUS STUDIES'
            ],
            'Department of Sociology and Social Work': [
                'BA. SOCIAL WORK', 'BA. SOCIAL WORK (PARALLEL)', 'BA. SOCIOLOGY', 'BA. SOCIOLOGY (PARALLEL)', 'MA. SOCIAL WORK', 'MA. SOCIOLOGY', 'MPHIL. SOCIAL WORK', 'MPHIL. SOCIOLOGY', 'PHD. SOCIOLOGY'
            ]
        },
        
        'KNUST School of Business': {
            'KNUST School of Business': [
                'BSC. BUSINESS ADMINISTRATION', 'BSC. BUSINESS ADMINISTRATION (PARALLEL)', 'DOCTOR OF BUSINESS ADMINISTRATION (DBA)', 'MASTER OF BUSINESS ADMINISTRATION (Full-time)', 
                'MASTER OF BUSINESS ADMINISTRATION (Part-Time)', 'MASTER OF BUSINESS ADMINISTRATION (Weekend)', 'MPHIL., BUSINESS ADMINISTRATION', 'MSC. BUSINESS AND DATA ANALYTICS', 'MSC. MARKETING ANALYTICS'
            ],
            'Department of Accounting and Finance': [
                'BSC. BUSINESS ADMINISTRATION (ACCOUNTING/BANKING AND FINANCE)', 'BSC. BUSINESS ADMINISTRATION (ACCOUNTING/BANKING AND FINANCE) (OBUASI CAMPUS)', 'BSC. BUSINESS ADMINISTRATION (ACCOUNTING/BANKING AND FINANCE) (PARALLEL)', 
                'MPHIL. ACCOUNTING', 'MPHIL. ACCOUNTING (TOP-UP)', 'MPHIL. FINANCE', 'MPHIL. FINANCE (TOP-UP)', 'MSC. ACCOUNTING AND FINANCE', 'MSC. FINANCE'
            ],
            'Department of Hospitality and Tourism Studies': [
                'BSC. HOSPITALITY AND TOURISM MANAGEMENT', 'BSC. HOSPITALITY AND TOURISM MANAGEMENT (PARALLEL)'
            ],
            'Department of Human Resource and Organizational Development': [
                'BSC. BUSINESS ADMINISTRATION (HUMAN RESOURCE MANAGEMENT/MANAGEMENT)', 'BSC. BUSINESS ADMINISTRATION (HUMAN RESOURCE MANAGEMENT/MANAGEMENT) (OBUASI CAMPUS)', 'BSC. BUSINESS ADMINISTRATION (HUMAN RESOURCE MANAGEMENT/MANAGEMENT) (PARALLEL)', 'MBA. HUMAN RESOURCE MANAGEMENT (FULL-TIME)', 
                'MBA. STRATEGIC MANAGEMENT AND MANAGMENT CONSULTING (FULL-TIME)', 'MBA. STRATEGIC MANAGEMENT AND MANAGMENT CONSULTING (TOPUP)', 'MPHIL. HUMAN RESOURCE MANAGEMENT', 'MPHIL. MANAGEMENT AND HUMAN RESOURCE STRATEGY', 'MPHIL. MANAGEMENT AND HUMAN RESOURCE STRATEGY (TOP UP)', 
                'MSC. CORPORATE GOVERNANCE AND STRATEGIC LEADERSHIP', 'MSC. MANAGEMENT AND HUMAN RESOURCE STRATEGY', 'PHD. BUSINESS AND MANAGEMENT', 'PHD. ORGANISATIONAL LEADERSHIP'
            ],
            'Department of Marketing and Corporate Strategy': [
                'BSC. BUSINESS ADMINISTRATION (MARKETING/INTERNATIONAL BUSINESS)', 'BSC. BUSINESS ADMINISTRATION (MARKETING/INTERNATIONAL BUSINESS) (OBUASI CAMPUS)', 'BSC. BUSINESS ADMINISTRATION (MARKETING/INTERNATIONAL BUSINESS) (PARALLEL)', 
                'MPHIL. BUSINESS AND MANAGEMENT', 'MPHIL. MARKETING', 'MPHIL. MARKETING (TOP-UP)', 'MSC. HEALTH ENTREPRENEURSHIP', 'MSC. MARKETING'
            ],
            'Department of Supply Chain and Information Systems': [
                'BSC. BUSINESS ADMINISTRATION (LOGISTICS AND SUPPLY CHAIN MANAGEMENT/BIT) (OBUASI CAMPUS)', 'BSC. BUSINESS ADMINISTRATION (LOGISTICS AND SUPPLY CHAIN MANAGEMENT/BIT) (PARALLEL)', 'BSC. BUSINESS ADMINISTRATION (LOGISTICS AND SUPPLY CHAIN MANAGEMENT/BUSINESS INFORMATION TECHNOLOGY)', 
                'MPHIL. LOGISTICS AND SUPPLY CHAIN MANAGEMENT', 'MPHIL. LOGISTICS AND SUPPLY CHAIN MANAGEMENT (TOP-UP)', 'MPHIL. PROCUREMENT AND SUPPLY CHAIN MANAGEMENT', 'MSC. AGRICULTURAL SUPPLY CHAIN MANAGEMENT', 
                'MSC. AIR TRANSPORTATION AND AVIATION MANAGEMENT', 'MSC. HEALTH SUPPLY CHAIN MANAGEMENT', 'MSC. LOGISTICS AND SUPPLY CHAIN MANAGEMENT', 'MSC. PHARMACEUTICAL LOGISTICS AND SUPPLY CHAIN MANAGEMENT', 'MSC. PROCUREMENT AND SUPPLY CHAIN MANAGEMENT'
            ]
        }
    }
}


for college, faculties in cohss_programmes.items():
    for faculty, departments in faculties.items():
        pprint({college: faculty})